interface=eth1 # Change to your internal interface
dhcp-range=10.10.10.50,10.10.10.150,12h
address=/portal.local/10.10.10.1
nftset=/google.com/youtube.com/gstatic.com/googlevideo.com/ytimg.com/4#inet#custom_portal#google_ips
