table inet custom_portal {
    set google_ips { type ipv4_addr; flags timeout; timeout 24h; }
    set allowed_clients { type ipv4_addr; flags timeout; }

    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        ip daddr 10.10.10.1 accept
        ip daddr @google_ips accept
        ip saddr @allowed_clients accept
        tcp dport 80 redirect to :80
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
        ct state established,related accept
        ip daddr @google_ips accept
        ip saddr @allowed_clients accept
        tcp dport 443 reject with tcp reset
    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        oifname "enp0s5" masquerade
    }
}
